/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    //    int n=4;
//    roll (n);
//    int[] arrDub={3, 2, 1, 5,2};
//    containsDuplicates (arrDub);

    public static  ArrayList roll (int n){
        ArrayList<Integer>listOfNumbers=new ArrayList<>();

        for( int i=0;i<n;i++){
            listOfNumbers.add((int)(Math.random()*6)+1);

        }
        System.out.println(listOfNumbers);
        return listOfNumbers;
    }
    public  boolean containsDuplicates(int []arr){
        for (int i=0;i< arr.length-1;i++){
            for (int j=i+1;j< arr.length;j++){
                if (arr[i] == arr[j]) {
                    return true;
                }//end if

            }//end internal for

        }// end external for

        return false;
    }//end containsDuplicates()



    public static double avg (int[]arr){
        // ArrayList<Integer>listOfNumbers=new ArrayList<>();
        double sum=0.0;

        for( int i=0;i<=arr.length-1;i++){
            // listOfNumbers.add((int)(Math.random()*6)+1);
            sum=sum+(double)arr[i];
        }
        System.out.println(sum);

        System.out.println(sum/arr.length);
        return sum/arr.length;
    }
    public static int sumMatrix(int [][]arr){
        ArrayList<Integer>listOfAvg=new ArrayList<>();
// int newSum=0;
        int sum=0;
        int avg=0;
        int lowestAvg=0;
        for (int i=0;i< arr.length;i++){
            for (int j=0;j< arr[i].length;j++){
                sum=sum+arr[i][j];
                listOfAvg.add(arr[i][j]);
            }//end internal for
            avg=sum/arr[i].length;
            System.out.println(sum);
            if(i==0){lowestAvg=avg;}


            if(avg<lowestAvg){lowestAvg=avg;
//  for (int j=0;j< arr[i].length-1;j++){
//  listOfAvg.indexOf(j)=arr[i][j];
//                  System.out.println(listOfAvg);

//         }//end intern
            }
            sum=0;
            avg=0;
        }// end external for
        // System.out.println(sum);
        System.out.println(lowestAvg);
        // System.out.println(listOfAvg);

        return lowestAvg;
        // return listOfAvg;
    }

}
