/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        Restaurant restaurant1=new Restaurant("Esraa",8,"$$$");
restaurant1.addReview("Batool",9);
        restaurant1.toString();
//        //        Restaurant restaurant2=new Restaurant();
////        Restaurant restaurant3=new Restaurant();
//        restaurant1.name="BB";
//        restaurant1.priceCategory="$$";
//        restaurant1.numberOfStars=5;


//        restaurant2.toString();
//        restaurant3.toString();


        //review


//        System.out.println();
    }
}
