/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

public static void main(String[] args) {
    //        System.out.println(new App().getGreeting());

    Path path = Paths.get("../resources/gates.js");

    System.out.print(linter(path));
}
    public static String linter(Path path) {
        String errorsLines="";
        BufferedReader reader = null;


        try {
            reader = Files.newBufferedReader(path);
            String line = reader.readLine();
            int lineNumber=1;
            while (line != null) {
                if(line.isEmpty() ||  line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else")|| line.endsWith(";") ){
                }
                else {
                    errorsLines = errorsLines +"Line "+lineNumber+ ": Missing semicolon."+"\n";

                }
                lineNumber++;
                line = reader.readLine();
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            return errorsLines;
        }




    }
}
