/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        File file=new File("gates.js");
        Scanner scanner=new Scanner(Scanner"gates.js");
        Scanner scan = new Scanner(new File("gates.js"));

        while (scanner.hasNextLine()){
//          String s=scanner.nextLine();
//System.out.println(s);
//             String   line = s.readLine();

//        Path path = Paths.get(s);
        }



        BufferedReader reader = null;
        // option 2
//
//        try {
//            reader = Files.newBufferedReader(path);
//            String line = reader.readLine();
//
//            while(line != null){
//                System.out.println("- "+line);
//                line = reader.readLine();
//            }
//        } catch (IOException ex){
//            ex.printStackTrace();
//        } finally {
//            if(reader != null) {
//                try {
//                    reader.close();
//                } catch(IOException e){
//                    System.out.println("an error occurred while closing the file");
//                }
//            }
//        }

    }
}
//java.nio.file.NoSuchFileException: resources/gates.js
//        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
//        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
//        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
//        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
//        at java.nio.file.Files.newByteChannel(Files.java:361)
//        at java.nio.file.Files.newByteChannel(Files.java:407)
//        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
//        at java.nio.file.Files.newInputStream(Files.java:152)
//        at java.nio.file.Files.newBufferedReader(Files.java:2784)
//        at java.nio.file.Files.newBufferedReader(Files.java:2816)
//        at linter.App.main(App.java:24)