/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
@Test
    public void testRestaurant(){
    Library classUnderTest = new Library();
    Restaurant restaurant1=new Restaurant();

    restaurant1.name="BB";
    restaurant1.priceCategory="$$";
    restaurant1.numberOfStars=5;
//    restaurant1.toString();
    System.out.println(restaurant1.toString());
    String expectedOutcome="Restaurant Name Is: BB\n" +
            "Restaurant Rate Is: 5\n" +
            "Restaurant Price Category Is: $$\n";
//    assertTrue(true);
    assertEquals(expectedOutcome,restaurant1.toString());
    }

@Test
    public void testReview(){
        //review
    Review review1=new Review();
    review1.body= "very good";
    review1.author= "me";
    review1.numberOfStars= 5;
    review1.numberOfStarsGiven= 5;
    review1.name= "BB";
    review1.priceCategory= "$$";
//    review1.toString();
    String expectedOutcome="Restaurant Name Is: BB\n" +
            "Restaurant Rate Is: 5\n" +
            "Restaurant Price Category Is: $$\n" +
            "Restaurant New Given  Rate Is: 5\n" +
            "Reviewed by : me\n" +
            "Review Is : very good";
    assertEquals(expectedOutcome,review1.toString());
//    assertTrue(true);
}
}
